### PR TITLE
Merge dask ml 1.6.0

### PR DESCRIPTION
**Pull request by zachary-mcpher**
Brings our ZEFR-INC/dask-ml fork of dask/dask-ml up to date with dask/dask-ml's v.1.6.0.

### CODE REVIEW

**Review by jamesbsilva — APPROVED** [review]
From what I can tell the parts related to CV are just adding typing and doctor stuff so I think should be compatible especially if all tests pass

**Review by tian-yi-zefr — COMMENTED** [review]
is there any particular files we need to review?

**Comment by zachary-mcpher** [comment]
> is there any particular files we need to review?

Nothing in particular, I've looked through most of the changes and I don't suspect any to be breaking. Some notable additions:
```
* Added :class:`dask_ml.decomposition.IncrementalPCA` for out-of-core / distributed incremental PCA (:pr:`619`)
* Scikit-Learn 0.23.0 or newer is now required
* Improved logging and monitoring in incremental model selection (:pr:`528`)
* Compatibility with Scikit-Learn 0.23.0 (:pr:`669`)
* * Added support for ``dask.dataframe`` objects in :class:`dask_ml.model_selection.HyperbandSearchCV` (:pr:`701`)
* Addition of `dask_ml.ensemble.BlockwiseVotingClassifier
* Addition of dask_ml.feature_extraction.CountVectorizer
```

**Review by tian-yi-zefr — APPROVED** [review]
let's try it!

**Review by zexuan-zhou — APPROVED** [review]
lgtm.

**Pull request merged**
